sls:
  ak: aliyun-sls-ak
  sk: aliyun-sls-sk
  endpoint: aliyun-sls-endpoint
  project: aliyun-sls-project
  logStore: aliyun-sls-logstore
es:
  hostname: es-host
  username: es-username
  password: es-password